name: CI/CD Docker & Dockerhub with actions v2

on: push # [push, pull_request]

jobs:
  benchmark:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: benchmarks the go code
      run: make benchmark

  test:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: tests the code
      run: make test
